on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 6 * *'

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: parse douban
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install urllib3
          python jd_dog.py